### ISSUE TITLE
List location of dependency

### ISSUE THREAD

**Issue by RichardLitt** [jslicense/licensee.js#14]
```sh
underscore@1.7.0
  NOT APPROVED
  Terms: Invalid license metadata
  Repository: git://github.com/jashkenas/underscore.git
  Homepage: http://underscorejs.org
  Author: Jeremy Ashkenas <jeremy@documentcloud.org>
  Contributors: None listed
```

It would be great to know where underscore@1.7.0 is being called - it is not the most recent version, and I suspect that many packages use the [old style](https://docs.npmjs.com/files/package.json#license) for declaring licenses in `package.json`s:

```sh
// Not valid metadata
{ "license" :
  { "type" : "ISC"
  , "url" : "https://opensource.org/licenses/ISC"
  }
}
```

While note SPDX approved, this shouldn't be flagging the same error as the others, because there is a license, at least. Alternatively to declaring where the dep is being called, this module could check for older license checks. 

This may be out of scope for this module.

**Comment by motet-a** [comment]
As a workaround, [`yarn why underscore`](https://yarnpkg.com/lang/en/docs/cli/why/) can explain why `underscore` is installed. I don't know if there is a similar command with `npm`.

**Comment by kemitchell** [comment]
<https://docs.npmjs.com/cli/ls> for `npm`.

**Comment by kemitchell** [comment]
@RichardLitt, the old, Ruby-style license arrays either were or weren't spec'd under some of the old CommonJS drafts, depending on who you ask. I don't believe objects were ever spec'd by anyone. npm's package spec went to SPDX pretty early.  It's been years and years now.

There are plenty of packages with licenses in header comments, or in `README`, or in `LICENSE` files, without corresponding metadata. It's nontrivial to identify and derive conclusions from that kind of unstructured data with software. Basically, it boils down to statistical methods and judgment calls about confidence levels. And folks end up going back to manually verify those automated conclusions when it matters.

Rather than dive down that rabbit hole, `licensee`, `npm`, and npmjs.com generally expect spec-compliant license data, and exert gentle pressure on maintainers to get it right. Since there will inevitably be packages that _don't_ get it right, including some old ones that are stable but also basically unmaintained---see <http://npm1k.org/>---the tools have to provide a workaround. In licensee that's the `whitelist` configuration property. If you come to your own conclusion about the terms for `underscore@1.7.0`, for example, you can put it in the whitelist, and licensee will `exit 0` again.

**Comment by RichardLitt** [comment]
I understand better now! Thank you. Agreed that it is nontrivial.
