### ISSUE TITLE
Shareable Config

### ISSUE THREAD

**Issue by adam-moss** [jslicense/licensee.js#17]
Related to #2 are there any plans to include an `extends` type property to support shareable configs?

**Comment by kemitchell** [comment]
@adam-moss, I'm not exactly sure what you mean by shareable configs. `licensee` currently loads any `.licensee.json` for configuration. You can produce that JSON file however you like.

**Comment by adam-moss** [comment]
So what I mean here is the

```js
{
    extends: [ "moduleA", "moduleB" ]
}
```

Type of pattern.  i.e. the project `.licensee.json` essentially imports its config from one or more other modules, so that a common baseline of whitelisted packages can be shared.

Does that make sense?

**Comment by kemitchell** [comment]
@adam-moss, thanks for clarifying.

I'm open to input from others, but I don't expect I'll putt any time on that kind of configuration.

Figuring out how to do that kind of system correctly may be a bigger and harder problem than `licensee` otherwise tries to solve. And I know from experience that programs with support for that kind of configuration---`eslint` comes to mind---cause all manner of headaches, in terms of making sure modularized configs are properly installed, reading from disk, etc. It's often a real pain to get them configured, and even when you do, and come back to a project later, it's pretty common for something to have shifted, creating a break.

I would much rather keep `licensee` as small and focused as possible, and let folks do whatever they want to do to compose the JSON or command line flag arguments for the configuration they want.

```json
{
  "scripts": {
    "prelicense": "node compose-config.js > .licensee.json",
    "license": "licensee"
  }
}
```

I might change my tune if someone managed to package up the functionality you're describing in a lean and focused package that we could rely on. But even then, I'm loathe to bring anything more in scope than I have to.
