### ISSUE TITLE
Support third-party assessments of package license?

### ISSUE THREAD

**Issue by kemitchell** [jslicense/licensee.js#32]
I've been thinking a bit about allowing `licensee` to use external "mappings" from `package@version` to SPDX ID, for those packages that have an SPDX-identified license, but haven't coded it correctly in `package.json`.

I find myself copying the same `whitelist` mappings from project to project. This could solve.

**Comment by kemitchell** [comment]
I suspect this would also address @ljharb's pain in #29.

**Comment by ljharb** [comment]
Kind of like how DefinitelyTyped lets you externally define types for a package that doesn't provide them, this would be a way to define a valid license for a package that doesn't provide one? SGTM.

**Comment by kemitchell** [comment]
@ljharb see https://github.com/jslicense/npm-license-corrections.json

**Comment by dabutvin** [comment]
FWIW, we have a similar initiative going on in clearlydefined. We overlay the corrections on scanned data.
see https://github.com/clearlydefined/curated-data/tree/master/curations/npm/npmjs/-
for the npms that have been curated to date

**Comment by kemitchell** [comment]
@dabutvin Those data files say "declared". Is that "declared" somewhere other than `package.json`, or are you just replicating the `package.json` properties?

**Comment by dabutvin** [comment]
It is matching the structure of what we call a definition so that any property can be overridden.

We have 'declared' license and 'discovered' licenses. While we may discover many licenses in a package looking file by file, there will be an all-up declared license.

Here is an example full definition for reference https://api.clearlydefined.io/definitions/npm/npmjs/-/glob/7.1.3
