### ISSUE TITLE
Idea: give 'packages' a more descriptive name

### ISSUE THREAD

**Issue by mikemaccana** [jslicense/licensee.js#71]
Firstly thanks for the useful tool! One small piece of feedback - a colleague messages me last week with:

> should i trust https://github.com/myco/myapp/blob/master/frontend/.licensee.json as the full list of packages/licenses?
> i would have thought there should be a lot more

This is despite me mentioning previously that `packages` is a list of exceptions, rather than a list of all packages.

I suspect my colleague (and I, when I first started using licensee) are not the only one confused by the key name `packages`. Giving it a more descriptive name might help eliminate the confusion!

Some better names might be:

 - `ignorePackages`
 - `ignore`
 - `exceptions`

etc. Anyway thanks for listening to the suggestion!

**Comment by kemitchell** [comment]
Hey, @mikemaccana. Thanks for the feedback.

I don't doubt your experience. I can understand how your colleague may have been confused. But to be honest, I'm reluctant to change our config file format again. Especially in any way that might break or confuse existing config files. Especially since this is the first I'm hearing of this confusion.

By default, `licensee` will report errors for all dependencies. Everything in `.licensee.json` is exceptions from there. Some of those exceptions are specific packages. Others are categories of licenses, or even specific licenses. We've named them accordingly.

Originally, I believe the property was called `whitelist`. But that made less and less sense as we added other ways to approve packages.

If you want a full report of all detected packages and licenses, run `licensee` and pipe it to a file.
